# Generated by Django 3.1.7 on 2021-03-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeuser',
            name='phone',
            field=models.BigIntegerField(default=1, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
