# Generated by Django 3.1.7 on 2021-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_auto_20210325_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='Телефон'),
        ),
    ]
