# Generated by Django 3.1.7 on 2021-03-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_auto_20210326_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='API Key'),
        ),
    ]
