# Generated by Django 3.1.7 on 2021-03-26 09:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_auto_20210326_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
